config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rizac/sdaas:
      branch: master
      repo: https://github.com/rizac/sdaas
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rizac/sdaas git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-cobalt-mau.sh
        container: qc.acc_pasty-ivory-shrimp
  QC.Doc:
    repos:
      github.com/rizac/sdaas find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-salmon-akita.sh
        container: qc.doc_bluesy-tangerine-fowl
      github.com/rizac/sdaas git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-gamboge-rottweiler.sh
        container: qc.doc_sloppy-black-monster
      github.com/rizac/sdaas markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-puce-mayfly.sh
        container: qc.doc_snippy-orchid-kudu
  QC.Lic:
    repos:
      github.com/rizac/sdaas licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-cardinal-squid.sh
        container: qc.lic_woozy-cinnabar-horse
  QC.Sec:
    repos:
      github.com/rizac/sdaas bandit:
        commands:
        - /usr/bin/env sh .sqa/script.silly-brown-spaniel.sh
        container: qc.sec_slaphappy-lilac-tortoise
  QC.Sty:
    repos:
      github.com/rizac/sdaas flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-white-dodo.sh
        container: qc.sty_shabby-rust-fly
  QC.Uni:
    repos:
      github.com/rizac/sdaas pytest:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-yellow-cow.sh
        container: qc.uni_craggy-amaranth-reindeer
  QC.Ver:
    repos:
      github.com/rizac/sdaas get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-razzmatazz-bee.sh
        container: qc.ver_hazy-periwinkle-uakari
timeout: 5400
